default:
  image: node:lts
  cache:
    key: node
    paths:
      - node_modules/
    policy: pull-push

stages:
  - preparar
  - run

os_dependencies:
  stage: preparar
  script:
    - apt-get update
    - apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
    - apt-get install -y ffmpeg

node_dependencies:
  stage: preparar
  script:
    - npm install
  cache:
    key: node
    paths:
      - node_modules/
    policy: pull-push


testando:
  stage: run
  cache:
    key: node
    paths:
      - node_modules/
    policy: pull-push
  before_script:
    - cp -f $TOKENS data/tokens.json
    - cp -f $RUN test.js
    - cp -f $CONFIG dada/config.json
  script:
    - node -v
    - npm -v
    - node test.js
